Repository global-platform/selfservice-base, pull requests merged in 2021-06, with the labels that each got.

#63 fix: Add missing provider
  Jenkinsfile
  terraform.tf
Labels: size/XS

#64 chore(deps): update terraform aws to v3.43.0
  terraform.tf
Labels: size/XS

#65 chore(deps): update terraform github.com/global-devops-terraform/vpc to v1.11.0
  vpc.tf
Labels: size/XS

#66 chore(deps): update terraform github.com/global-devops-terraform/vpc to v1.12.0
  vpc.tf
Labels: size/XS

#67 chore(deps): update terraform aws to v3.44.0
  terraform.tf
Labels: size/XS

#69 chore(deps): update terraform aws to v3.46.0
  terraform.tf
Labels: size/XS, ✅ Approved

#71 chore(deps): update terraform aws to v3.47.0
  terraform.tf
Labels: size/XS, ✅ Approved

#70 chore(deps): update terraform github.com/global-devops-terraform/vpc to v1.13.1
  vpc.tf
Labels: size/XS, ✅ Approved

#72 chore(deps): update terraform github.com/global-devops-terraform/vpc to v1.14.0
  vpc.tf
Labels: size/XS, ✅ Approved, 🔍 Ready for Review

#74 chore(deps): update terraform github.com/global-devops-terraform/bastion to v0.68.0
  bastion.tf
Labels: size/XS, ✅ Approved

#62 feat: Remove peering
  peering.tf
Labels: size/S, ✅ Approved

#75 chore(deps): update terraform github.com/global-devops-terraform/global-info to v0.48.0
  common.tf
Labels: size/XS, ✅ Approved
