Repository global-platform/selfservice-base, pull requests merged in 2021-09, with the labels that each got.

#103 chore(deps): update terraform aws to v3.57.0
  terraform.tf
Labels: ✅ Approved, size/XS

#104 chore(deps): update terraform github.com/global-devops-terraform/vpc to v1.21.0
  vpc.tf
Labels: 🔍 Ready for Review, ✅ Approved, size/XS

#105 chore(deps): update terraform aws to v3.58.0
  terraform.tf
Labels: 🔍 Ready for Review, ✅ Approved, size/XS

#106 feat: add HA for prod NAT
  vpc.tf
Labels: ✅ Approved, size/XS

#107 feat: Remove bastion
  README.md
  bastion.tf
  outputs.tf
Labels: 🔍 Ready for Review, size/L

#108 fix: Tidy
  README.md
  config.tf
  variables.tf
Labels: 🔍 Ready for Review, size/S

#111 chore(deps): update terraform aws to v3.59.0
  terraform.tf
Labels: ✅ Approved, size/XS

#109 chore(deps): update terraform github.com/global-devops-terraform/global-info to v0.50.0
  common.tf
Labels: 🔍 Ready for Review, size/XS

#110 chore(deps): update terraform github.com/global-devops-terraform/vpc to v1.21.1
  vpc.tf
Labels: ✅ Approved, size/XS
