Repository global-platform/selfservice-base, pull requests merged in 2021-02, with the labels that each got.

#19 fix(deps): update terraform global-devops-terraform/eks to v0.48.1
  main.tf
Labels: size/XS

#20 fix: Jenkinsfile
  Jenkinsfile
Labels: size/XS

#21 fix(deps): update terraform github.com/global-devops-terraform/global-info to v0.40.0
  common.tf
Labels: size/XS

#22 fix(deps): update terraform github.com/global-devops-terraform/global-info to v0.41.0
  common.tf
Labels: size/XS

#24 fix: README
  README.md
Labels: size/M

#23 fix(deps): update terraform github.com/global-devops-terraform/vpc to v1.7.0
  README.md
  variables.tf
  vars/dev.tfvars
  vars/preprod.tfvars
  vars/prod.tfvars
  vars/qa.tfvars
  vpc.tf
Labels: size/S

#25 fix(deps): update terraform github.com/global-devops-terraform/dns-zone to v0.18.0
  route53.tf
Labels: size/XS

#28 fix(deps): update terraform github.com/global-devops-terraform/global-info to v0.42.0
  common.tf
Labels: size/XS

#26 fix(deps): update terraform github.com/global-devops-terraform/vpc to v1.8.0
  vpc.tf
Labels: size/XS

#27 fix(deps): update terraform github.com/global-devops-terraform/bastion to v0.58.0
  bastion.tf
Labels: size/XS

#29 fix(deps): update terraform github.com/global-devops-terraform/bastion to v0.58.1
  bastion.tf
Labels: size/XS

#30 fix(deps): update terraform github.com/global-devops-terraform/bastion to v0.59.0
  bastion.tf
Labels: size/XS

#31 fix(deps): update terraform github.com/global-devops-terraform/global-info to v0.43.0
  common.tf
Labels: size/XS

#32 fix(deps): update terraform github.com/global-devops-terraform/dns-zone to v0.18.1
  route53.tf
Labels: size/XS

#33 fix(deps): update terraform github.com/global-devops-terraform/bastion to v0.59.1
  bastion.tf
Labels: size/XS
