Repository global-platform/selfservice-base, pull requests merged in 2021-01, with the labels that each got.

#8 fix: upgraded to latest module versions
  bastion.tf
  bucket.tf
  common.tf
  main.tf
  peering.tf
  route53.tf
  vpc.tf
Labels: size/S

#11 fix(deps): update terraform global-devops-terraform/eks to v0.47.0
  main.tf
Labels: size/XS

#9 fix(deps): update terraform global-devops-terraform/bastion to v0.57.0
  bastion.tf
Labels: size/XS

#6 fix: remove name tag
  bastion.tf
Labels: size/XS, 🔍 Ready for Review

#10 fix(deps): update terraform global-devops-terraform/dns-zone to v0.16.0
  route53.tf
Labels: size/XS

#12 fix(deps): update terraform global-devops-terraform/bastion to v0.57.1
  bastion.tf
Labels: size/XS

#13 fix(deps): update terraform global-devops-terraform/global-info to v0.37.1
  common.tf
Labels: size/XS

#14 fix(deps): update terraform global-devops-terraform/vpc to v1.6.1
  vpc.tf
Labels: size/XS

#16 fix(deps): update terraform global-devops-terraform/eks to v0.47.1
  main.tf
  provider.tf
Labels: size/S

#15 fix(deps): update terraform global-devops-terraform/global-info to v0.38.0
  common.tf
Labels: size/XS

#17 fix(deps): update terraform global-devops-terraform/global-info to v0.39.1
  common.tf
Labels: size/XS

#18 fix(deps): update terraform global-devops-terraform/dns-zone to v0.17.0
  route53.tf
Labels: size/XS
